- hosts: galaxy_hosts
  pre_tasks:
    - name: Create shed_tools directory
      file:
        state: "{{ item.state }}"
        path: "{{ item.path }}"
        owner: galaxy
        group: users
      with_items:
        - {path: "{{ galaxy_user_home }}/shed_tools", state: "directory" }
        - {path: "{{ galaxy_mutable_data_dir }}/tool-data", state: "directory" }
        - {path: "{{ galaxy_mutable_config_dir }}/tool-data", state: "directory" }
        - {path: "{{ galaxy_log_dir }}", state: "directory" }
      become: yes

    - name: Copy custom_tool_conf xml file
      copy:
        src: custom_tool_conf.xml
        dest: "{{ galaxy_mutable_config_dir }}"
        owner: galaxy
        group: users
      become: yes

  roles:
    - role: common
    - role: ansible-galaxy
      become: yes
      become_user: galaxy
