- hosts: galaxy_hosts
  become: true
  handlers:
    - name: restart galaxy
      supervisorctl:
        name: galaxy
        state: restarted

  roles:
    - role: common
    - role: geerlingguy.pip
    - role: usegalaxy-eu.supervisor
    - role: geerlingguy.nginx
    - role: galaxyproject.cvmfs

  post_tasks:
    - name: Set tool_data_table_config_path to CVMFS one
      replace:
        path: "{{ galaxy_config_dir }}/galaxy.yml"
        regexp: '^    tool_data_table_config_path.*'
        replace: '    tool_data_table_config_path: /cvmfs/data.galaxyproject.org/byhand/location/tool_data_table_conf.xml,/cvmfs/data.galaxyproject.org/managed/location/tool_data_table_conf.xml'
      notify: restart galaxy
