- hosts: galaxy_hosts
  roles:
    - role: common
    - role: ansible-galaxy-os
      become: yes
  post_tasks:
    - name: Remove useless packages from the cache
      apt:
        autoclean: yes
      become: yes
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
      become: yes
