---
# Install the base operating system requirements for running Galaxy
- include: g4t_os_setup.yml

# Install the base PostgreSQL requirements and configure it
- include: g4t_db_setup.yml

# Install Galaxy
- include: g4t_galaxy.yml

# Configure production services including nginx, uwsgi, supervisor.
- include: g4t_extras.yml

# Install tools from toolshed
#- include: g4t_tools.yml

#- hosts: localhost
#  connection: local
#  vars:
#    galaxy_server_dir: /home/galaxy/server
#    galaxy_config_dir: /home/galaxy/config
#    galaxy_mutable_config_dir: /home/galaxy/var/opt/galaxy/config
#    galaxy_mutable_data_dir: /home/galaxy/var/opt/galaxy/data
#    galaxy_vcs: git
#    galaxy_repo: https://github.com/galaxyproject/galaxy.git
#    galaxy_changeset_id: release_16.04
#    galaxy_manage_download: no
#  roles:
#    - role: ansible-galaxy-os
#      become: yes
#    - role: ansible-galaxy
