galaxy_user_name: "galaxy"
galaxy_user_home: "/home/galaxy"
galaxy_home_dir: "{{ galaxy_user_home }}"
galaxy_server_dir: "{{ galaxy_user_home }}/server"
galaxy_config_dir: "{{ galaxy_user_home }}/config"
galaxy_config_file: "{{ galaxy_config_dir }}/galaxy.ini"
galaxy_venv_dir: "{{ galaxy_server_dir }}/.venv"
galaxy_log_dir: "{{ galaxy_user_home }}/log"
