# vars from ansible-galaxy-os role
galaxy_user_name: "galaxy"
galaxy_user_home: "/home/galaxy"

# vars from ansible-postgres role
pg_db_name: galaxy
pg_user: galaxy
pg_password: null

# vars from ansible-galaxy role
galaxy_home_dir: "{{ galaxy_user_home }}"
galaxy_server_dir: "{{ galaxy_user_home }}/server"
galaxy_config_dir: "{{ galaxy_user_home }}/config"
galaxy_config_file: "{{ galaxy_config_dir }}/galaxy.ini"
galaxy_venv_dir: "{{ galaxy_server_dir }}/.venv"
galaxy_log_dir: "{{ galaxy_user_home }}/log"
galaxy_release_id: "release_17.09"

admin_users: 'admin@example.com'
brand: 'G4T'
galaxy_mutable_config_dir: "{{ galaxy_user_home }}/config"
galaxy_mutable_data_dir: "{{ galaxy_user_home }}/data"
galaxy_changeset_id: "{{ galaxy_release_id | default('release_16.04') }}"
galaxy_force_checkout: yes
galaxy_config:
  "server:main":
    host: 0.0.0.0
  "app:main":
    conda_ensure_channels: conda-forge,r,bioconda,iuc
    conda_auto_install: True
    conda_auto_init: True
    database_connection: "postgresql:///galaxy?host=/var/run/postgresql"
    brand: "{{ brand }}"
    admin_users: "{{ admin_users }}"
    allow_user_impersonation: True
    require_login: True
    allow_user_creation: True
    shed_tool_data_path: "{{ galaxy_mutable_data_dir }}/tool-data"
    tool_config_file: "{{ galaxy_server_dir }}/config/tool_conf.xml.sample,{{ galaxy_mutable_config_dir }}/custom_tool_conf.xml,{{ galaxy_shed_tool_conf_file }}"
    cleanup_job: onsuccess
    environment_setup_file: "{{galaxy_mutable_config_dir }}/custom_env.sh"
    nginx_x_accel_redirect_base: '/_x_accel_redirect'

#vars from ansible-gx-extras
supervisor_venv_dir: "{{ galaxy_user_home }}/supervisor/venv"
supervisor_config_dir: "{{ galaxy_user_home }}/supervisor/config"
uwsgi_threads: 4
galaxy_web_processes: 4
galaxy_handler_processes: 2